/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { fadeOnBeforeCompile } from "../utils/fadeMaterial";
import { useFrame } from "@react-three/fiber";

const Cloud = ({ sceneOpacity, ...props }) => {
  const { nodes, materials } = useGLTF("models/cloud/cloud.gltf");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mball001.geometry}>
        <meshStandardMaterial
          ref={materialRef}
          // {...materials["lambert2SG.001"]}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
    </group>
  );
};

export default Cloud;

useGLTF.preload("models/cloud/cloud.gltf");
