/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/eagle-dc34aa716318405d974883908181fb41
Title: Eagle
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
// import { useControls } from "leva";

const Eagle = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/eagle/eagle.glb");
  const { actions } = useAnimations(animations, group);

  // const { animation } = useControls("Eagle Fly Free", {
  //   animation: { value: "", options: Object.keys(actions) },
  // });
  // useEffect(() => {
  //   if (animation && actions[animation]) {
  //     Object.values(actions).forEach((action) => action.stop());
  //     actions[animation].play();
  //   }
  // }, [animation, actions]);

  useEffect(() => {
    actions["Animation"].play();
  }, []);

  console.log("actions", actions);
  return (
    <group ref={group} {...props} dispose={null} rotation-y={Math.PI}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.035}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="eagle_18"
                position={[0, 2, 3]}
                rotation={[-0.1, 0, 0]}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["Material.002"]}
                    skeleton={nodes.Object_7.skeleton}
                    morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
                  />
                  <meshStandardMaterial color="white" />
                  <group name="Object_4_17" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Eagle;

useGLTF.preload("/models/eagle/eagle.glb");
